apiVersion: v1
kind: Pod
metadata:
  name: postgres-exporter
spec:
  containers:
    - name: postgres-exporter
      image: bitnami/postgres-exporter:latest
      ports:
        - containerPort: 9187
      env:
        - name: DATA_SOURCE_URI
          value: "postgresql://mahdi:1234@postgres:5432/bank"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187