apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - postgres
      containers:
      - name: postgres
        image: db-proj-postgres
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: "mahdi"
          - name: POSTGRES_PASSWORD
            value: "1234"
          - name: POSTGRES_DB
            value: "bank"
        ports:
          - containerPort: 5432
      
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter
        # imagePullPolicy: IfNotPresent
        env:
          - name: DATA_SOURCE_NAME
            value: "postgresql://mahdi:1234@localhost:5432/bank"
        ports:
          - containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
